packages:
  - apps/*
  - packages/*
  - examples/*

catalog:
  zod: 4.6.5
  typescript: 7.0.2
  vitest: 5.0.1
  vite: 8.3.0
  "@types/node": ^26.0.0
  drizzle-orm: 0.45.3
  drizzle-kit: 0.31.11
  pg: 8.23.0
  "@types/pg": 8.23.1
  "@aws-sdk/client-secrets-manager": 3.1137.0
  "@aws-sdk/client-s3": 3.1137.0
  "@aws-sdk/s3-request-presigner": 3.1137.0
  "@aws-sdk/client-sqs": 3.1137.0
  "@aws-sdk/client-application-auto-scaling": 3.1137.0
  "@aws-sdk/client-cloudwatch": 3.1137.0
  "@aws-sdk/client-ecs": 3.1137.0
  "@nestjs/common": 12.0.4
  "@nestjs/core": 12.0.4
  "@nestjs/platform-express": 12.0.4
  "@nestjs/testing": 12.0.4
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  nestjs-pino: 5.2.0
  pino-http: 11.0.0
  pino: 10.3.1
  supertest: 7.2.2
  "@types/supertest": 7.2.1
  "@opentelemetry/api": 1.9.1
  "@opentelemetry/sdk-node": 0.222.0
  "@opentelemetry/auto-instrumentations-node": 0.80.0
  "@opentelemetry/exporter-trace-otlp-proto": 0.222.0
  "@opentelemetry/exporter-metrics-otlp-proto": 0.222.0
  "@opentelemetry/exporter-logs-otlp-proto": 0.222.0
  "@opentelemetry/sdk-metrics": 2.11.0
  "@opentelemetry/sdk-logs": 0.222.0
  "@opentelemetry/resources": 2.11.0
  "@opentelemetry/semantic-conventions": 1.43.0
  import-in-the-middle: 3.5.1
  better-auth: 1.7.5
  "@better-auth/passkey": 1.7.5
  "@better-auth/sso": 1.7.5
  "@better-auth/core": 1.7.5

allowBuilds:
  esbuild: true
  sharp: true
  "@swc/core": false
  protobufjs: false
  ssh2: false
  cpu-features: false
