import type { Principal } from '@ocso/auth';
import type { HttpCapabilityMethod } from '../catalog/index.js';

/**
 * Ask OCSO runtime contracts (PM/research/12 §4–§6). The model sees two meta
 * tools; reads run through the real API route as the user, and every write
 * becomes a server-built confirmation card that only the user's click runs.
 */

/**
 * Where a card stands. CONFIRMING (the single-use claim while its route runs) is reported as PENDING. UNKNOWN: the
 * route was run but did not answer in time (or the confirm never finished), so it may or may not have applied.
 */
export type CardStatus = 'PENDING' | 'EXECUTED' | 'SUBMITTED' | 'REJECTED' | 'EXPIRED' | 'FAILED' | 'STALE' | 'UNKNOWN';

/** One field a write would change. */
export interface CardChange {
  label: string;
  before: string | null;
  after: string;
}

export interface CardChecker {
  id: string;
  name: string;
  role: string;
  /** The checker the card offers first (a colleague on the object's own team when there is one). */
  suggested: boolean;
}

/**
 * A credential the card's own form asks for (PM/research/12 §9): the user types it into a password field on the
 * card; the model never sees or supplies it. `generate`: left blank, OCSO generates it ("leave blank to generate").
 */
export interface CardCredentialField {
  key: string;
  label: string;
  hint?: string | undefined;
  required: boolean;
  generate?: boolean | undefined;
}

/** A secret the route generated, handed to the confirming user once in the confirm response (never stored). */
export interface RevealedSecret {
  key: string;
  label: string;
  value: string;
}

/** The confirmation card (BUILD.md "Card"): what the drawer renders and the confirm endpoint returns. */
export interface ActionCard {
  id: string;
  tool: string;
  title: string;
  summary: string;
  /** direct: applies on confirm. stop: pause / disable / revoke, applies at once, never approval. governed: submitted to a checker. */
  kind: 'direct' | 'stop' | 'governed';
  object?: { kind: string; id: string; name: string; href?: string | undefined } | undefined;
  changes: CardChange[];
  warnings: string[];
  approval?:
    | {
        objectKind: string;
        checkers: CardChecker[];
        /** Nobody else may approve it: Ask OCSO never offers bootstrap self-approval, the card links to the UI instead. */
        noEligibleChecker: boolean;
        uiHref?: string | undefined;
      }
    | undefined;
  /** Credentials the user enters on the card itself (names only: values are never on a card). */
  credentials?: CardCredentialField[] | undefined;
  expiresAt: string;
  status: CardStatus;
  result?: { message: string; href?: string | undefined; proposalId?: string | undefined } | undefined;
}

/** One request to a real API route (path already filled, query and body split from the model's flat arguments). */
export interface CapabilityCall {
  method: HttpCapabilityMethod;
  path: string;
  query?: Record<string, unknown> | undefined;
  body?: unknown;
}

export interface CapabilityResponse {
  status: number;
  /** Parsed JSON body (null for 204). Error bodies are `{ error: { category, code, message, details } }`. */
  body: unknown;
}

/** What a delegated request is bound to (and audited with): the thread and the card, or the read's tool call. */
export interface DelegationScope {
  threadId: string;
  cardId?: string | undefined;
  callId?: string | undefined;
  correlationId: string;
}

/**
 * Runs an API route in-process as the user (PM/research/12 §6). The API's implementation sends it over a
 * private loopback listener with a single-use delegation token bound to the user's session, the thread and the
 * card or call, so guards, validation, team scoping, approvals and audit are exactly the UI's.
 */
export interface CapabilityRunner {
  call(principal: Principal, scope: DelegationScope, call: CapabilityCall): Promise<CapabilityResponse>;
}

/** The API error body, when a route refused. */
export interface ApiErrorBody {
  category: string;
  code: string;
  message: string;
  details?: Record<string, unknown> | undefined;
}

export function apiError(body: unknown): ApiErrorBody | null {
  const error = (body as { error?: unknown } | null)?.error;
  if (!error || typeof error !== 'object') return null;
  const e = error as Record<string, unknown>;
  return {
    category: typeof e['category'] === 'string' ? e['category'] : 'internal',
    code: typeof e['code'] === 'string' ? e['code'] : 'error',
    message: typeof e['message'] === 'string' ? e['message'] : 'The request failed',
    details: e['details'] && typeof e['details'] === 'object' ? (e['details'] as Record<string, unknown>) : undefined,
  };
}

/** What confirm answers: the card, plus secrets generated by the route, shown once (this response only). */
export type ConfirmedCard = ActionCard & { reveal?: RevealedSecret[] | undefined };
