/**
 * BlobStore contract (docs/07 §6, ADR-011). PostgreSQL keeps media metadata and
 * keys; bytes live here. Access to customers/staff is always through
 * short-lived signed URLs or the authorized API.
 */
export interface BlobPutInput {
  key: string;
  data: Uint8Array;
  contentType: string;
  /** Retention class drives lifecycle rules (docs/15 §8). */
  retention?: 'CONVERSATION_MEDIA' | 'EXPORT' | 'TEMP' | undefined;
}

export interface BlobObject {
  key: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
}

export interface BlobStore {
  readonly driver: 'local' | 's3';
  put(input: BlobPutInput): Promise<BlobObject>;
  get(key: string): Promise<{ data: Uint8Array; contentType: string; sizeBytes: number }>;
  head(key: string): Promise<{ contentType: string; sizeBytes: number } | null>;
  delete(key: string): Promise<void>;
  /** Short-lived HTTPS URL for downloads (browser, channel providers). */
  signedGetUrl(key: string, ttlSeconds: number): Promise<string>;
}

const KEY_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9/_.=-]{0,500}$/;

/** Keys are generated by OCSO; reject anything that could escape a directory. */
export function assertSafeKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error('invalid blob key');
  }
}

/** Build a media key: media/2026/09/<conversation>/<id>.<ext> */
export function mediaKey(conversationId: string, id: string, ext: string, at = new Date()): string {
  const y = at.getUTCFullYear();
  const m = String(at.getUTCMonth() + 1).padStart(2, '0');
  const safeExt = ext.replace(/[^a-z0-9]/gi, '').slice(0, 8) || 'bin';
  return `media/${y}/${m}/${conversationId}/${id}.${safeExt}`;
}
