/**
 * BlobStore contract (docs/archive/specs/07 §6, ADR-011). PostgreSQL keeps media metadata and
 * keys; bytes live here. Access to customers/staff is always through
 * short-lived signed URLs or the authorized API.
 */
export interface BlobPutInput {
  key: string;
  data: Uint8Array;
  contentType: string;
  /** Retention class drives lifecycle rules (docs/archive/specs/15 §8). */
  retention?: 'CONVERSATION_MEDIA' | 'EXPORT' | 'TEMP' | undefined;
}

export interface BlobObject {
  key: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
}

export interface BlobStore {
  /** Name of the driver that built it (BLOB_DRIVER); display and logs only. */
  readonly driver: string;
  put(input: BlobPutInput): Promise<BlobObject>;
  get(key: string): Promise<{ data: Uint8Array; contentType: string; sizeBytes: number }>;
  head(key: string): Promise<{ contentType: string; sizeBytes: number } | null>;
  delete(key: string): Promise<void>;
  /** Short-lived HTTPS URL for downloads (browser, channel providers). */
  signedGetUrl(key: string, ttlSeconds: number): Promise<string>;
  /**
   * Stores whose signed URLs point at OCSO's own `/blobs/<key>` route verify
   * them here (the signature is the authorization). Stores with their own
   * signed URLs (S3 presigning) omit it, and the route refuses every request.
   */
  verifySignedGet?(key: string, exp: number, sig: string, nowSeconds: number): boolean;
}

/**
 * A blob storage driver: registered by name, selected by BLOB_DRIVER. `check`
 * lists missing or inconsistent settings (start-up fails naming every one);
 * `create` builds the process-wide store. `Env` is the deployment
 * environment the driver reads.
 */
export interface BlobDriverDefinition<Env = Readonly<Record<string, unknown>>> {
  /** BLOB_DRIVER value that selects this driver, e.g. `s3`. */
  readonly name: string;
  readonly check?: ((env: Env) => readonly string[]) | undefined;
  readonly create: (env: Env) => BlobStore;
}

const KEY_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9/_.=-]{0,500}$/;

/** Keys are generated by OCSO; reject anything that could escape a directory. */
export function assertSafeKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error('invalid blob key');
  }
}

/** Build a media key: media/2026/09/<conversation>/<id>.<ext> */
export function mediaKey(conversationId: string, id: string, ext: string, at = new Date()): string {
  const y = at.getUTCFullYear();
  const m = String(at.getUTCMonth() + 1).padStart(2, '0');
  const safeExt = ext.replace(/[^a-z0-9]/gi, '').slice(0, 8) || 'bin';
  return `media/${y}/${m}/${conversationId}/${id}.${safeExt}`;
}
