'use server';

import { refresh } from 'next/cache';
import { Permission } from '@ocso/auth';
import { z } from 'zod';
import { createChannel, updateChannel, type Channel } from '../api/channels';
import { describeApiError } from '../api/errors';
import { getSession } from '../session';
import type { ActionResult } from './models';

/** What the "next steps" panel needs after a save (never secret values). */
export type SavedChannel = Pick<Channel, 'id' | 'kind' | 'name' | 'publicKey' | 'webhookPath' | 'status'>;

const Fields = z.object({
  name: z.string().trim().min(1, 'Enter a name').max(120),
  settings: z.record(z.string(), z.unknown()),
  /** Only secrets the admin typed or generated; blank ones are kept (edit) or generated by the API (create). */
  secrets: z.record(z.string().regex(/^[A-Za-z0-9_]{1,64}$/), z.string().min(1).max(8_000)),
  defaultAgentId: z.uuid().nullable(),
  status: z.enum(['ACTIVE', 'DISABLED', 'DRAFT']),
});
const Create = Fields.extend({ kind: z.string().regex(/^[A-Z_]{2,32}$/) });

async function run<I>(schema: z.ZodType<I>, raw: unknown, call: (input: I) => Promise<Channel>): Promise<ActionResult<SavedChannel>> {
  const parsed = schema.safeParse(raw);
  if (!parsed.success) return { ok: false, message: parsed.error.issues.map((i) => `${i.path.join('.') || 'input'}: ${i.message}`).join('; ') };
  const session = await getSession();
  if (!session) return { ok: false, message: 'Your session has ended. Sign in again.' };
  if (!session.permissions.has(Permission.CHANNELS_MANAGE)) return { ok: false, message: 'Your role cannot manage channels.' };
  try {
    const c = await call(parsed.data);
    refresh();
    return { ok: true, data: { id: c.id, kind: c.kind, name: c.name, publicKey: c.publicKey, webhookPath: c.webhookPath, status: c.status } };
  } catch (err) {
    return { ok: false, message: describeApiError(err) };
  }
}

/** POST /v1/channels. The API validates settings and secrets when the channel is ACTIVE. */
export async function createChannelAction(input: z.input<typeof Create>): Promise<ActionResult<SavedChannel>> {
  return run(Create, input, createChannel);
}

/** PATCH /v1/channels/:id: settings replace the stored object; only typed secrets rotate. */
export async function updateChannelAction(id: string, input: z.input<typeof Fields>): Promise<ActionResult<SavedChannel>> {
  return run(z.object({ id: z.uuid(), body: Fields }), { id, body: input }, (i) => updateChannel(i.id, i.body));
}
