'use server';

import { refresh } from 'next/cache';
import { Permission } from '@ocso/auth';
import { z } from 'zod';
import { createChannel, testChannel, updateChannel, type Channel, type ChannelTestResult } from '../api/channels';
import { ApiError, describeApiError } from '../api/errors';
import { getSession } from '../session';
import type { ActionResult } from './models';

/** What the "next steps" panel needs after a save (never secret values). */
/** The saved channel (settings are non-secret: the next steps fill a setup file's `{{settings.<key>}}` from them). */
export type SavedChannel = Pick<Channel, 'id' | 'kind' | 'name' | 'publicKey' | 'webhookPath' | 'status' | 'settings'> & {
  /** Keys OCSO generated that the admin must copy now (e.g. the web chat secret key); returned once on create. */
  revealedSecrets?: Record<string, string> | undefined;
};

const Fields = z.object({
  name: z.string().trim().min(1, 'Enter a name').max(120),
  settings: z.record(z.string(), z.unknown()),
  /** Only secrets the admin typed or generated; blank ones are kept (edit) or generated by the API (create). */
  secrets: z.record(z.string().regex(/^[A-Za-z0-9_]{1,64}$/), z.string().min(1).max(8_000)),
  /** Deprecated (routers decide who answers): accepted, never sent. */
  defaultAgentId: z.uuid().nullable().optional(),
});
const Approval = z.union([z.object({ checkerId: z.uuid(), reason: z.string().trim().min(3).max(500) }), z.object({ bootstrap: z.literal(true), reason: z.string().trim().min(3).max(500).optional() })]);
export type ChannelApprovalChoice = z.input<typeof Approval>;
/** Any kind the API's registry knows (open; the API refuses unregistered kinds). */
const Create = Fields.extend({ kind: z.string().regex(/^[A-Z][A-Z0-9_]{1,39}$/) });

async function run<I>(
  schema: z.ZodType<I>,
  raw: unknown,
  call: (input: I) => Promise<(Channel & { revealedSecrets?: Record<string, string> | undefined }) | { proposal: unknown }>,
): Promise<ActionResult<SavedChannel | null>> {
  const parsed = schema.safeParse(raw);
  if (!parsed.success) return { ok: false, message: parsed.error.issues.map((i) => `${i.path.join('.') || 'input'}: ${i.message}`).join('; ') };
  const session = await getSession();
  if (!session) return { ok: false, message: 'Your session has ended. Sign in again.' };
  if (!session.permissions.has(Permission.CHANNELS_MANAGE)) return { ok: false, message: 'Your role cannot manage channels.' };
  try {
    const c = await call(parsed.data);
    refresh();
    // 202: the change became a proposal (nothing changed yet).
    if ('proposal' in c) return { ok: true, data: null };
    const revealed = c.revealedSecrets && Object.keys(c.revealedSecrets).length ? { revealedSecrets: c.revealedSecrets } : {};
    return { ok: true, data: { id: c.id, kind: c.kind, name: c.name, publicKey: c.publicKey, webhookPath: c.webhookPath, status: c.status, settings: c.settings, ...revealed } };
  } catch (err) {
    return { ok: false, message: describeApiError(err), code: err instanceof ApiError ? err.code : undefined };
  }
}

/** POST /v1/channels: a draft (inert); the API validates settings and secrets when it is activated. */
export async function createChannelAction(input: z.input<typeof Create>): Promise<ActionResult<SavedChannel | null>> {
  return run(Create, input, ({ defaultAgentId: _a, ...body }) => createChannel(body));
}

/**
 * PATCH /v1/channels/:id: settings replace the stored object; only typed secrets rotate. A draft changes
 * directly; an approved channel needs `approval` (the answer is then a proposal: `data` null).
 */
export async function updateChannelAction(id: string, input: z.input<typeof Fields>, approval?: ChannelApprovalChoice): Promise<ActionResult<SavedChannel | null>> {
  return run(z.object({ id: z.uuid(), body: Fields, approval: Approval.optional() }), { id, body: input, approval }, (i) => {
    const { defaultAgentId: _a, ...body } = i.body;
    return updateChannel(i.id, { ...body, ...(i.approval ? { approval: i.approval } : {}) });
  });
}

/** POST /v1/channels/:id/test: checks the saved credentials with the provider (read-only; no message is sent). */
export async function testChannelAction(id: string): Promise<ActionResult<ChannelTestResult>> {
  const parsed = z.uuid().safeParse(id);
  if (!parsed.success) return { ok: false, message: 'Unknown channel.' };
  const session = await getSession();
  if (!session) return { ok: false, message: 'Your session has ended. Sign in again.' };
  if (!session.permissions.has(Permission.CHANNELS_MANAGE)) return { ok: false, message: 'Your role cannot manage channels.' };
  try {
    return { ok: true, data: await testChannel(parsed.data) };
  } catch (err) {
    return { ok: false, message: describeApiError(err) };
  }
}
