import { z } from 'zod';
import type { ChannelKindDescriptor } from '../contract/descriptor.js';
import { WebChatSettings } from './config.js';

export const WEBCHAT_DESCRIPTOR: ChannelKindDescriptor = {
  kind: 'WEBCHAT',
  label: 'Web chat',
  description: 'An embeddable chat widget for your website or app; add one script tag with the channel key.',
  mark: { code: 'WB', name: 'Web chat' },
  settingsSchema: z.toJSONSchema(WebChatSettings, { io: 'input' }) as Record<string, unknown>,
  secrets: [
    { key: 'visitorTokenSecret', label: 'Visitor token secret', required: true, hint: 'Signs anonymous visitor sessions. Generated by OCSO when left empty.', generate: 'server' },
    {
      key: 'hostJwtSecret',
      label: 'Host identity secret',
      required: false,
      hint: 'Optional HS256 secret (32+ characters) your site uses to sign identify() tokens for signed-in customers.',
      generate: 'client',
    },
    {
      key: 'secretKey',
      label: 'Secret key',
      required: false,
      hint: 'Server-side key (sk_…) your backend uses to mint session passes and that protects held user tokens. Keep it on your server; never ship it in a page or app.',
      generate: 'server',
      prefix: 'sk_',
      reveal: 'once',
    },
  ],
  identitySetting: { label: 'host jwt', keys: ['hostJwtIssuer'] },
  setupGuide: [
    {
      title: 'Save the channel',
      body: 'Choose the auth mode and branding below and save. OCSO generates the visitor token secret (and the secret key, shown once) when you leave them empty.',
      form: true,
    },
    { title: 'Add the embed tag', body: 'Add the embed tag to every page that should show the chat launcher.' },
    { title: 'Restrict the sites', body: 'List every site that uses the widget under Allowed origins; with the list empty, any site may embed it.' },
    {
      title: 'Recognise signed-in customers (optional)',
      body: 'Verify their tokens with your identity provider’s JWKS URL, or have your site sign an HS256 token with the host identity secret and pass it to identify().',
    },
    {
      title: 'Apps and authorised clients (optional)',
      body: 'Set the auth mode to client or user and have your backend mint a session pass with the secret key (see the Server tab).',
    },
  ],
  inboundWebhook: false,
  embeddable: true,
};
