import { z } from 'zod';
import type { ChannelKindDescriptor } from '../contract/descriptor.js';
import { WebChatSettings } from './config.js';

export const WEBCHAT_DESCRIPTOR: ChannelKindDescriptor = {
  kind: 'WEBCHAT',
  label: 'Web chat',
  description: 'An embeddable chat widget for your website or app; add one script tag with the channel key.',
  mark: { code: 'WB', name: 'Web chat' },
  settingsSchema: z.toJSONSchema(WebChatSettings, { io: 'input' }) as Record<string, unknown>,
  secrets: [
    { key: 'visitorTokenSecret', label: 'Visitor token secret', required: true, hint: 'Signs anonymous visitor sessions. Generated by OCSO when left empty.', generate: 'server' },
    {
      key: 'hostJwtSecret',
      label: 'Host identity secret',
      required: false,
      hint: 'Optional HS256 secret (32+ characters) your site uses to sign identify() tokens for signed-in customers.',
      generate: 'client',
    },
  ],
  identitySetting: { label: 'host jwt', keys: ['hostJwtIssuer'] },
  setupSteps: [
    'Add the embed tag to every page that should show the chat launcher.',
    'List every site that uses the widget under Allowed origins; with the list empty, any site may embed it.',
    'To recognise signed-in customers, have your site sign an HS256 token with the host identity secret and pass it to the widget’s identify().',
  ],
  inboundWebhook: false,
  embeddable: true,
};
