import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync, randomUUID, sign, verify, type KeyObject } from 'node:crypto';
import type { Checkpoint } from './contract.js';

/**
 * Ed25519 signing for audit checkpoints and exports (PM/research/11 §6.1).
 * The private key is a PKCS#8 PEM file (AUDIT_SIGNING_KEY_FILE, generated by
 * Compose keygen); the key id is the first 16 hex characters of the sha256 of
 * the public key's SPKI DER, so anyone holding the public key can match it.
 */
export interface AuditPublicKey {
  keyId: string;
  algorithm: 'Ed25519';
  publicKeyPem: string;
}

export interface AuditSigner extends AuditPublicKey {
  /** base64 Ed25519 signature over the UTF-8 message. */
  sign(message: string): string;
  /**
   * Retired public keys that older checkpoints, exports and reports were signed
   * with (AUDIT_TRUSTED_PUBLIC_KEYS_FILE). Verification trusts them; nothing new is signed with them.
   */
  retiredKeys?: readonly AuditPublicKey[] | undefined;
}

/** The current key and every retired one: what signatures verify against. */
export function trustedKeys(signer: AuditSigner | null): AuditPublicKey[] {
  if (!signer) return [];
  const current = publicKeyOf(signer);
  return [current, ...(signer.retiredKeys ?? []).filter((k) => k.keyId !== current.keyId)];
}

export function keyIdOf(publicKey: KeyObject): string {
  return createHash('sha256').update(publicKey.export({ type: 'spki', format: 'der' })).digest('hex').slice(0, 16);
}

/** A signer from a PKCS#8 PEM private key; refuses anything but Ed25519. */
export function loadSigningKey(pem: string): AuditSigner {
  const privateKey = createPrivateKey(pem);
  if (privateKey.asymmetricKeyType !== 'ed25519') throw new Error('the audit signing key must be an Ed25519 private key (PKCS#8 PEM)');
  const publicKey = createPublicKey(privateKey);
  return {
    keyId: keyIdOf(publicKey),
    algorithm: 'Ed25519',
    publicKeyPem: publicKey.export({ type: 'spki', format: 'pem' }).toString(),
    sign: (message) => sign(null, Buffer.from(message, 'utf8'), privateKey).toString('base64'),
  };
}

/** A fresh Ed25519 private key as PKCS#8 PEM (Compose keygen does the same). */
export function generateSigningKeyPem(): string {
  return generateKeyPairSync('ed25519').privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();
}

export function publicKeyOf(signer: AuditPublicKey): AuditPublicKey {
  return { keyId: signer.keyId, algorithm: 'Ed25519', publicKeyPem: signer.publicKeyPem };
}

/** A public key from its SPKI PEM (verification only). */
export function parsePublicKey(publicKeyPem: string): AuditPublicKey {
  const key = createPublicKey(publicKeyPem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error('not an Ed25519 public key');
  return { keyId: keyIdOf(key), algorithm: 'Ed25519', publicKeyPem: key.export({ type: 'spki', format: 'pem' }).toString() };
}

/** Every SPKI PEM public key in a bundle (concatenated PEM blocks, e.g. AUDIT_TRUSTED_PUBLIC_KEYS_FILE). */
export function parsePublicKeys(bundle: string): AuditPublicKey[] {
  const blocks = bundle.match(/-----BEGIN PUBLIC KEY-----[\s\S]*?-----END PUBLIC KEY-----/g) ?? [];
  if (!blocks.length && bundle.trim()) throw new Error('no PEM public key found in the trusted keys bundle');
  return blocks.map(parsePublicKey);
}

export function verifySignature(publicKeyPem: string, message: string, signature: string): boolean {
  try {
    return verify(null, Buffer.from(message, 'utf8'), createPublicKey(publicKeyPem), Buffer.from(signature, 'base64'));
  } catch {
    return false;
  }
}

/** The signed text of a checkpoint. */
export function checkpointMessage(c: Pick<Checkpoint, 'upToPosition' | 'chainHash' | 'createdAt'>): string {
  return `ocso-audit-checkpoint\n${c.upToPosition}\n${c.chainHash}\n${c.createdAt.toISOString()}`;
}

export function signCheckpoint(signer: AuditSigner, at: { upToPosition: number; chainHash: string }, createdAt: Date = new Date(), id: string = randomUUID()): Checkpoint {
  // Stores keep millisecond precision; sign exactly what will be read back.
  const created = new Date(Math.floor(createdAt.getTime()));
  return { id, upToPosition: at.upToPosition, chainHash: at.chainHash, createdAt: created, keyId: signer.keyId, signature: signer.sign(checkpointMessage({ ...at, createdAt: created })) };
}

export function verifyCheckpoint(c: Checkpoint, keys: readonly AuditPublicKey[]): 'VALID' | 'INVALID' | 'UNKNOWN_KEY' {
  const key = keys.find((k) => k.keyId === c.keyId);
  if (!key) return 'UNKNOWN_KEY';
  return verifySignature(key.publicKeyPem, checkpointMessage(c), c.signature) ? 'VALID' : 'INVALID';
}
