import type { AuditStoreDriverDefinition } from '@ocso/audit-store';
import type { BlobDriverDefinition, BlobStore } from '@ocso/blob';
import type { WorkerEnv } from '@ocso/config';
import { secrets as secretsTable, type Db } from '@ocso/db';
import type { DeploymentDriverDefinition } from '@ocso/deployment';
import type { EmailDriverDefinition } from '@ocso/email';
import type { QueueAdapter, QueueDriverDefinition, QueueNotifier, SqlClient } from '@ocso/queue';
import type { SecretMetadata, SecretRow, SecretRowStore, SecretStore, SecretStoreDriverDefinition } from '@ocso/secrets';
import { eq } from 'drizzle-orm';
import { DriverRegistry, type NamedDriver } from './drivers/registry.js';
import { FIRST_PARTY_PLUGINS } from './first-party.js';
import { contributions, type DriverEnv, type OcsoPlugin } from './plugin.js';

/** The infrastructure driver registries of a process, filled from the plugins. */
export interface DriverRegistries {
  email: DriverRegistry<EmailDriverDefinition>;
  blob: DriverRegistry<BlobDriverDefinition<DriverEnv>>;
  secrets: DriverRegistry<SecretStoreDriverDefinition<DriverEnv>>;
  queue: DriverRegistry<QueueDriverDefinition<DriverEnv>>;
  deployment: DriverRegistry<DeploymentDriverDefinition<WorkerEnv>>;
  audit: DriverRegistry<AuditStoreDriverDefinition<DriverEnv, never>>;
}

export function createDriverRegistries(plugins: readonly OcsoPlugin[] = FIRST_PARTY_PLUGINS): DriverRegistries {
  const fill = <D extends NamedDriver>(registry: DriverRegistry<D>, drivers: readonly D[]): DriverRegistry<D> => {
    for (const driver of drivers) registry.register(driver);
    return registry;
  };
  return {
    email: fill(new DriverRegistry('EMAIL_DRIVER', 'email'), contributions(plugins, 'emailDrivers')),
    blob: fill(new DriverRegistry('BLOB_DRIVER', 'blob'), contributions(plugins, 'blobDrivers')),
    secrets: fill(new DriverRegistry('SECRETS_DRIVER', 'secrets'), contributions(plugins, 'secretsDrivers')),
    queue: fill(new DriverRegistry('QUEUE_DRIVER', 'queue'), contributions(plugins, 'queueDrivers')),
    deployment: fill(new DriverRegistry('DEPLOYMENT_DRIVER', 'deployment'), contributions(plugins, 'deploymentDrivers')),
    audit: fill(new DriverRegistry('AUDIT_DRIVER', 'audit store'), contributions(plugins, 'auditStoreDrivers')),
  };
}

interface CheckedDriver<E> extends NamedDriver {
  readonly check?: ((env: E) => readonly string[]) | undefined;
}

/** Problems with one `*_DRIVER` selection: an unregistered name, or the driver's own settings checks. */
function selectionProblems<E, D extends CheckedDriver<E>>(registry: DriverRegistry<D>, name: string, env: E): string[] {
  if (!registry.has(name)) return [registry.unknown(name)];
  return [...(registry.get(name).check?.(env) ?? [])];
}

function fail(problems: readonly string[]): void {
  if (problems.length) throw new Error(`Invalid OCSO configuration:\n${problems.map((p) => `  - ${p}`).join('\n')}`);
}

/** The driver `name` selects, after its settings checks passed (throws listing every problem). */
export function selectDriver<E, D extends CheckedDriver<E>>(registry: DriverRegistry<D>, name: string, env: E): D {
  fail(selectionProblems(registry, name, env));
  return registry.get(name);
}

/**
 * Start-up check (api and worker): BLOB_DRIVER, SECRETS_DRIVER, QUEUE_DRIVER
 * and AUDIT_DRIVER each name a registered driver whose settings are complete.
 * Throws one error listing every problem. EMAIL_DRIVER is checked by
 * resolveEmailConfig, which also resolves the email secrets.
 */
export function assertDrivers(env: DriverEnv, drivers: DriverRegistries = createDriverRegistries()): void {
  fail([
    ...selectionProblems(drivers.blob, env.BLOB_DRIVER, env),
    ...selectionProblems(drivers.secrets, env.SECRETS_DRIVER, env),
    ...selectionProblems(drivers.queue, env.QUEUE_DRIVER, env),
    ...auditProblems(env, drivers),
  ]);
}

/** AUDIT_DRIVER's selection and settings, plus the signing key production requires (ADR-032). */
function auditProblems(env: DriverEnv, drivers: DriverRegistries): string[] {
  const problems = selectionProblems(drivers.audit, env.AUDIT_DRIVER, env);
  if (env.NODE_ENV === 'production' && !env.AUDIT_SIGNING_KEY_FILE && !env.AUDIT_SIGNING_KEY) {
    problems.push('AUDIT_SIGNING_KEY_FILE (an Ed25519 private key, PKCS#8 PEM) or AUDIT_SIGNING_KEY is required in production (Compose: generated by keygen)');
  }
  return problems;
}

/** The worker also selects a deployment driver (its leader applies scaling). */
export function assertWorkerDrivers(env: WorkerEnv, drivers: DriverRegistries = createDriverRegistries()): void {
  fail([
    ...selectionProblems(drivers.blob, env.BLOB_DRIVER, env),
    ...selectionProblems(drivers.secrets, env.SECRETS_DRIVER, env),
    ...selectionProblems(drivers.queue, env.QUEUE_DRIVER, env),
    ...selectionProblems(drivers.deployment, env.DEPLOYMENT_DRIVER, env),
    ...auditProblems(env, drivers),
  ]);
}

/**
 * Adapter selection by configuration (docs/02 §6, build rule §17): the
 * registered driver each `*_DRIVER` names builds the adapter. This package is
 * the only place that knows which infrastructure the deployment uses.
 */
export function createSecretStore(env: DriverEnv, db: Db, drivers: DriverRegistries = createDriverRegistries()): SecretStore {
  return selectDriver(drivers.secrets, env.SECRETS_DRIVER, env).create(env, { rows: new DrizzleSecretRows(db) });
}

export function createBlobStore(env: DriverEnv, drivers: DriverRegistries = createDriverRegistries()): BlobStore {
  return selectDriver(drivers.blob, env.BLOB_DRIVER, env).create(env);
}

export function createQueue(
  env: DriverEnv,
  sql: SqlClient,
  workerId: string,
  notifier?: QueueNotifier,
  drivers: DriverRegistries = createDriverRegistries(),
): QueueAdapter {
  return selectDriver(drivers.queue, env.QUEUE_DRIVER, env).create(env, { sql, workerId, notifier });
}

/** SecretRowStore over the `secrets` table. */
class DrizzleSecretRows implements SecretRowStore {
  constructor(private readonly db: Db) {}

  async insert(row: SecretRow): Promise<void> {
    await this.db.insert(secretsTable).values(toDb(row));
  }

  async update(ref: string, patch: Pick<SecretRow, 'ciphertext' | 'rotatedAt' | 'version' | 'expiresAt'>): Promise<void> {
    await this.db
      .update(secretsTable)
      .set({
        ciphertext: patch.ciphertext,
        rotatedAt: patch.rotatedAt ? new Date(patch.rotatedAt) : null,
        version: patch.version,
        expiresAt: patch.expiresAt ? new Date(patch.expiresAt) : null,
      })
      .where(eq(secretsTable.ref, ref));
  }

  async get(ref: string): Promise<SecretRow | null> {
    const [row] = await this.db.select().from(secretsTable).where(eq(secretsTable.ref, ref));
    return row ? fromDb(row) : null;
  }

  async list(): Promise<SecretMetadata[]> {
    const rows = await this.db.select().from(secretsTable);
    return rows.map((r) => {
      const { ciphertext: _c, externalId: _e, ...meta } = fromDb(r);
      return meta;
    });
  }

  async delete(ref: string): Promise<void> {
    await this.db.delete(secretsTable).where(eq(secretsTable.ref, ref));
  }
}

function toDb(row: SecretRow): typeof secretsTable.$inferInsert {
  return {
    ref: row.ref,
    name: row.name,
    kind: row.kind,
    usedBy: row.usedBy,
    ciphertext: row.ciphertext,
    externalId: row.externalId,
    version: row.version,
    createdAt: new Date(row.createdAt),
    rotatedAt: row.rotatedAt ? new Date(row.rotatedAt) : null,
    expiresAt: row.expiresAt ? new Date(row.expiresAt) : null,
  };
}

function fromDb(r: typeof secretsTable.$inferSelect): SecretRow {
  return {
    ref: r.ref,
    name: r.name,
    kind: r.kind as SecretRow['kind'],
    usedBy: r.usedBy,
    ciphertext: r.ciphertext,
    externalId: r.externalId,
    version: r.version,
    createdAt: r.createdAt.toISOString(),
    rotatedAt: r.rotatedAt?.toISOString() ?? null,
    expiresAt: r.expiresAt?.toISOString() ?? null,
  };
}
