import { sql } from 'drizzle-orm';
import { bigint, check, date, index, integer, jsonb, pgTable, primaryKey, text, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { id, ts } from './columns.js';
import { users } from './identity.js';

/**
 * The exception report (PM/research/11 §7, ADR-033): everything that went
 * around or wrong in the controls during a period, frozen as `content` with
 * its sha256 `content_hash`. A holder of exceptions.sign signs it with the
 * audit signing key (Ed25519). Migration 0028's trigger rejects every DELETE,
 * any UPDATE of a SIGNED or SUPERSEDED report, and any UPDATE of a draft other
 * than signing it or superseding it by a regenerated report — so a signed
 * report is immutable and a draft's content never changes.
 *
 * Weekly periods never overlap: 0028 adds an exclusion constraint on
 * tstzrange(period_start, period_end) over WEEKLY reports that are not
 * SUPERSEDED (drizzle cannot express it; the unique index below is its subset).
 */
export const exceptionReports = pgTable(
  'exception_reports',
  {
    id: id(),
    kind: text().$type<'WEEKLY' | 'ADHOC'>().notNull(),
    periodStart: ts('period_start').notNull(),
    periodEnd: ts('period_end').notNull(),
    status: text().$type<'DRAFT' | 'SIGNED' | 'SUPERSEDED'>().notNull().default('DRAFT'),
    /** The frozen report (ExceptionReportContent); canonical JSON of it is what content_hash covers. */
    content: jsonb().$type<Record<string, unknown>>().notNull(),
    /** sha256 hex of canonicalJson(content). */
    contentHash: text().notNull(),
    generatedAt: ts('generated_at').notNull().defaultNow(),
    /** Null = generated by the scheduler. */
    generatedBy: uuid().references(() => users.id),
    signedAt: ts('signed_at'),
    signedBy: uuid().references(() => users.id),
    signNote: text(),
    /** base64 Ed25519 over the signed message (signing.ts: the spec's six lines, the attestation and the note's hash). */
    signature: text(),
    keyId: text(),
    /** The signer's public key (SPKI PEM) at signing: the report stays verifiable and exportable after key rotation. */
    publicKeyPem: text(),
    /** Flags the signer acknowledged (attestation.ts), part of the signed message. */
    attestation: text().array().notNull().default(sql`'{}'::text[]`),
    /** The regenerated report that replaced this draft (no FK: set in the same transaction that inserts it). */
    supersededBy: uuid(),
  },
  (t) => [
    check('exception_reports_kind_ck', sql`${t.kind} IN ('WEEKLY','ADHOC')`),
    check('exception_reports_status_ck', sql`${t.status} IN ('DRAFT','SIGNED','SUPERSEDED')`),
    check('exception_reports_period_ck', sql`${t.periodEnd} > ${t.periodStart}`),
    check(
      'exception_reports_signed_ck',
      sql`${t.status} <> 'SIGNED' OR (${t.signedAt} IS NOT NULL AND ${t.signedBy} IS NOT NULL AND ${t.signature} IS NOT NULL AND ${t.keyId} IS NOT NULL AND ${t.publicKeyPem} IS NOT NULL)`,
    ),
    check('exception_reports_superseded_ck', sql`${t.status} <> 'SUPERSEDED' OR ${t.supersededBy} IS NOT NULL`),
    // One current weekly report per period start (the exclusion constraint forbids any overlap).
    uniqueIndex('exception_reports_weekly_uq').on(t.kind, t.periodStart).where(sql`${t.kind} = 'WEEKLY' AND ${t.status} <> 'SUPERSEDED'`),
    index('exception_reports_period_idx').on(t.periodStart, t.id),
  ],
);

/**
 * Daily table sizes (the storage-sample leader task) behind GET /v1/system/storage:
 * growth per table and the ClickHouse guidance. `rows` is the planner's estimate
 * for large tables (exact for small ones); `bytes` includes indexes and TOAST.
 * Audit-store tables are sampled too, named `audit_store.<table>`.
 */
export const storageSamples = pgTable(
  'storage_samples',
  {
    day: date({ mode: 'string' }).notNull(),
    tableName: text().notNull(),
    rows: bigint({ mode: 'number' }).notNull(),
    bytes: bigint({ mode: 'number' }),
    sampledAt: ts('sampled_at').notNull().defaultNow(),
  },
  (t) => [primaryKey({ name: 'storage_samples_pk', columns: [t.day, t.tableName] }), index('storage_samples_table_idx').on(t.tableName, t.day)],
);

/**
 * Hourly roll-ups of health_samples (the health-rollup leader task): raw samples
 * are kept two days, roll-ups a year. Component rows summarise that component's
 * samples; the `availability` row holds the per-minute uptime verdict (database
 * and workers together, telemetry/uptime.ts) so 30-day uptime survives the raw prune.
 */
export const healthSampleRollups = pgTable(
  'health_sample_rollups',
  {
    hour: ts('hour').notNull(),
    component: text().notNull(),
    samples: integer().notNull().default(0),
    ok: integer().notNull().default(0),
    degraded: integer().notNull().default(0),
    down: integer().notNull().default(0),
    /** Minutes judged (availability) or minutes with at least one sample (components). */
    minutes: integer().notNull().default(0),
    /** Minutes judged up (availability) or minutes with no DOWN sample (components). */
    upMinutes: integer().notNull().default(0),
    lastDownAt: ts('last_down_at'),
    latencyAvgMs: integer(),
    latencyP95Ms: integer('latency_p95_ms'),
    latencyMaxMs: integer(),
    rolledAt: ts('rolled_at').notNull().defaultNow(),
  },
  (t) => [primaryKey({ name: 'health_sample_rollups_pk', columns: [t.hour, t.component] }), index('health_sample_rollups_component_idx').on(t.component, t.hour)],
);
