/**
 * Unit tests for scripts/check-source-guards.mjs (T1.1.2). Run: node --test scripts/test/
 * Each test builds a throwaway workspace in the OS temp dir and runs the CLI against it.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { extractImports, findCycles } from '../check-source-guards.mjs';

const SCRIPT = join(dirname(fileURLToPath(import.meta.url)), '..', 'check-source-guards.mjs');
const roots = [];
after(() => roots.forEach((r) => rmSync(r, { recursive: true, force: true })));

/** A minimal clean workspace: domain ← auth ← api, plus a web app. Extra files/manifests override. */
function fixture({ files = {}, manifests = {} } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'ocso-guards-'));
  roots.push(root);
  const baseManifests = {
    'packages/domain': { name: '@ocso/domain' },
    'packages/auth': { name: '@ocso/auth', dependencies: { '@ocso/domain': 'workspace:*' } },
    'apps/api': { name: '@ocso/api', dependencies: { '@ocso/auth': 'workspace:*', '@ocso/domain': 'workspace:*' } },
    'apps/web': { name: '@ocso/web', dependencies: { '@ocso/domain': 'workspace:*' } },
  };
  const baseFiles = {
    'packages/domain/src/index.ts': "export const x = 1;\n",
    'packages/auth/src/index.ts': "import { x } from '@ocso/domain';\nexport const y = x;\n",
    'apps/api/src/main.ts': "import { y } from '@ocso/auth';\nimport type { Z } from './types.js';\nconsole.log(y);\n",
    'apps/api/src/types.ts': 'export type Z = string;\n',
    'apps/web/src/page.tsx': "import { x } from '@ocso/domain';\nexport default () => x;\n",
  };
  for (const [dir, manifest] of Object.entries({ ...baseManifests, ...manifests })) {
    mkdirSync(join(root, dir), { recursive: true });
    writeFileSync(join(root, dir, 'package.json'), JSON.stringify(manifest));
  }
  for (const [path, text] of Object.entries({ ...baseFiles, ...files })) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), text);
  }
  return root;
}

function run(root) {
  const res = spawnSync(process.execPath, [SCRIPT, '--json', '--root', root], { encoding: 'utf8' });
  assert.equal(res.stderr, '', res.stderr);
  return { code: res.status, report: JSON.parse(res.stdout) };
}

const lines = (n) => Array.from({ length: n }, (_, i) => `export const v${i} = ${i};`).join('\n') + '\n';

describe('check-source-guards', () => {
  test('a clean workspace passes', () => {
    const { code, report } = run(fixture());
    assert.equal(code, 0);
    assert.equal(report.ok, true);
    assert.equal(report.scanned, 5);
    assert.deepEqual(report.violations, []);
    assert.deepEqual(report.cycles, []);
  });

  test('a file over 500 lines fails', () => {
    const { code, report } = run(fixture({ files: { 'packages/auth/src/huge.ts': lines(501) } }));
    assert.equal(code, 1);
    assert.deepEqual(report.files, [{ path: 'packages/auth/src/huge.ts', lines: 501, status: 'FAIL' }]);
  });

  test('a file over 300 lines only warns', () => {
    const { code, report } = run(fixture({ files: { 'apps/api/src/big.ts': lines(301), 'apps/api/src/ok.ts': lines(300) } }));
    assert.equal(code, 0);
    assert.equal(report.warnings, 1);
    assert.deepEqual(report.files, [{ path: 'apps/api/src/big.ts', lines: 301, status: 'WARN' }]);
  });

  test('tests, declaration files and generated files are exempt from the size limit', () => {
    const root = fixture({
      files: {
        'packages/auth/src/big.test.ts': lines(900),
        'packages/auth/src/types.d.ts': lines(900),
        'packages/auth/src/gen.ts': `// @generated by a tool. Do not edit.\n${lines(900)}`,
      },
    });
    const { code, report } = run(root);
    assert.equal(code, 0);
    assert.deepEqual(report.files, []);
  });

  test('a package without src/ (Next.js layout) is scanned from its root, minus tests and configs', () => {
    const { code, report } = run(
      fixture({
        manifests: { 'apps/site': { name: '@ocso/site' } },
        files: {
          'apps/site/app/page.tsx': lines(501),
          'apps/site/next.config.ts': lines(900),
          'apps/site/e2e/flow.ts': lines(900),
          'apps/site/lib/api.ts': "import { boot } from '@ocso/api';\nexport const b = boot;\n",
        },
      }),
    );
    assert.equal(code, 1);
    assert.deepEqual(report.files, [{ path: 'apps/site/app/page.tsx', lines: 501, status: 'FAIL' }]);
    assert.deepEqual(report.violations.map((v) => `${v.rule} ${v.at}`), ['app-imports-app apps/site/lib/api.ts:1']);
  });

  test('a package importing an app fails (by name and by relative path)', () => {
    const { code, report } = run(
      fixture({
        files: {
          'packages/auth/src/bad.ts': "import { boot } from '@ocso/api';\nexport const b = boot;\n",
          'packages/auth/src/bad2.ts': "export { z } from '../../../apps/api/src/types.js';\n",
        },
      }),
    );
    assert.equal(code, 1);
    const rules = report.violations.map((v) => `${v.rule} ${v.at}`).sort();
    assert.deepEqual(rules, ['package-imports-app packages/auth/src/bad.ts:1', 'package-imports-app packages/auth/src/bad2.ts:1']);
  });

  test('an app importing another app fails, including dynamic imports and package.json deps', () => {
    const { code, report } = run(
      fixture({
        files: { 'apps/web/src/lazy.ts': "export const load = () => import(\n  '@ocso/api/client'\n);\n" },
        manifests: { 'apps/web': { name: '@ocso/web', dependencies: { '@ocso/domain': 'workspace:*', '@ocso/api': 'workspace:*' } } },
      }),
    );
    assert.equal(code, 1);
    const rules = report.violations.map((v) => `${v.rule} ${v.at}`).sort();
    assert.deepEqual(rules, ['app-imports-app apps/web/package.json', 'app-imports-app apps/web/src/lazy.ts:2']);
  });

  test('@ocso/domain importing another @ocso package fails', () => {
    const { code, report } = run(
      fixture({
        files: { 'packages/domain/src/leak.ts': "import type {\n  Principal,\n} from '@ocso/auth';\nexport type P = Principal;\n" },
      }),
    );
    assert.equal(code, 1);
    assert.equal(report.violations.length, 1);
    assert.equal(report.violations[0].rule, 'domain-imports-workspace');
    assert.equal(report.violations[0].at, 'packages/domain/src/leak.ts:3');
    // The same edge also closes a cycle only if declared; here it is source-only, so no cycle.
    assert.deepEqual(report.cycles, []);
  });

  test('relative imports into a sibling package fail', () => {
    const { code, report } = run(fixture({ files: { 'packages/auth/src/peek.ts': "import { x } from '../../domain/src/index.js';\nexport const p = x;\n" } }));
    assert.equal(code, 1);
    assert.equal(report.violations[0].rule, 'relative-cross-workspace');
  });

  test('imports inside comments, strings of other calls and template literals are ignored', () => {
    const src = [
      "// import { a } from '@ocso/api';",
      "/* export * from '@ocso/api'; */",
      "const doc = `import x from '@ocso/api'`;",
      "const re = /from '@ocso\\/api'/;",
      "const ratio = total / count / 2; import { real } from '@ocso/domain';",
    ].join('\n');
    assert.deepEqual(
      extractImports(src).map((i) => i.specifier),
      ['@ocso/domain'],
    );
  });

  test('dependency cycles between workspace packages are detected', () => {
    const { code, report } = run(
      fixture({
        manifests: {
          'packages/domain': { name: '@ocso/domain' },
          'packages/auth': { name: '@ocso/auth', dependencies: { '@ocso/domain': 'workspace:*', '@ocso/queue': 'workspace:*' } },
          'packages/queue': { name: '@ocso/queue', devDependencies: { '@ocso/db': 'workspace:*' } },
          'packages/db': { name: '@ocso/db', dependencies: { '@ocso/auth': 'workspace:*' } },
        },
      }),
    );
    assert.equal(code, 1);
    assert.equal(report.cycles.length, 1);
    assert.deepEqual(report.cycles[0].path, ['@ocso/auth', '@ocso/queue', '@ocso/db', '@ocso/auth']);
  });

  describe('plugin boundary', () => {
    /** A composition root listing two plugin packages (and a core package that also contributes). */
    const pluginFixture = (files = {}) =>
      fixture({
        manifests: {
          'packages/bootstrap': { name: '@ocso/bootstrap' },
          'packages/channels': { name: '@ocso/channels' },
          'packages/queue': { name: '@ocso/queue' },
          'packages/application': { name: '@ocso/application' },
        },
        files: {
          'packages/bootstrap/src/first-party.ts':
            "export const FIRST_PARTY_PLUGINS = [\n  { name: '@ocso/channels', channels: [] },\n  { name: '@ocso/queue' },\n  { name: '@ocso/application' },\n];\n",
          'packages/bootstrap/src/drivers.ts': "import type { QueueDriverDefinition } from '@ocso/queue';\nexport const kafka: QueueDriverDefinition = { name: 'kafka', create: () => null };\n",
          'packages/channels/src/acme/adapter.ts': "export class AcmeAdapter {\n  readonly kind = 'ACME_CHAT' as const;\n}\n// kind: 'IN_A_COMMENT'\n",
          'packages/channels/src/beta/descriptor.ts': "export const beta = { kind: 'BETA_SMS', label: 'Beta' };\n",
          'packages/channels/src/beta/descriptor.test.ts': "export const t = { kind: 'TEST_ONLY' };\n",
          'packages/queue/src/pg.ts': "export class PgQueue {\n  readonly driver = 'postgres' as const;\n}\n",
          // A core package's own declarations are scanned as core, never harvested.
          'packages/application/src/actors.ts': "export const actor = { kind: 'AGENT' };\n",
          ...files,
        },
      });

    test('derives kinds and driver names from the plugins the composition root lists', () => {
      const { code, report } = run(pluginFixture());
      assert.equal(code, 0);
      assert.deepEqual(report.pluginBoundary.plugins, ['@ocso/channels', '@ocso/queue']);
      assert.deepEqual(report.pluginBoundary.kinds, ['ACME_CHAT', 'BETA_SMS']);
      assert.deepEqual(report.pluginBoundary.drivers, ['kafka', 'postgres']);
      assert.deepEqual(report.pluginBoundary.violations, []);
    });

    test('core code naming a kind, a per-kind key or a driver (in driver context) fails with file:line', () => {
      const { code, report } = run(
        pluginFixture({
          'apps/api/src/route.ts': "export const isAcme = (k: string) => k === 'ACME_CHAT';\nexport const labels = {\n  BETA_SMS: 'Beta',\n};\n",
          'apps/web/components/mark.tsx': 'export const M = () => <Mark kind="BETA_SMS" />;\n',
          'packages/application/src/queue.ts':
            "export const fast = (q: { driver: string }) => q.driver === 'postgres';\nexport const source = 'postgres'; // a word, not a driver selection\n",
        }),
      );
      assert.equal(code, 1);
      assert.deepEqual(
        report.pluginBoundary.violations.map((v) => `${v.rule} ${v.at} ${v.literal}`),
        [
          'plugin-kind apps/api/src/route.ts:1 ACME_CHAT',
          'plugin-key apps/api/src/route.ts:3 BETA_SMS',
          'plugin-kind apps/web/components/mark.tsx:1 BETA_SMS',
          'plugin-driver packages/application/src/queue.ts:1 postgres',
        ],
      );
      assert.match(report.pluginBoundary.violations[0].message, /declared by @ocso\/channels/);
    });

    test('seeds, tests and plugin packages may name kinds; a reasoned escape opts one line out', () => {
      const { code, report } = run(
        pluginFixture({
          'apps/api/src/seed/steps.ts': "export const k = 'ACME_CHAT';\n",
          'apps/api/src/route.test.ts': "export const k = 'ACME_CHAT';\n",
          'packages/channels/src/use.ts': "export const k = 'ACME_CHAT';\n",
          'apps/api/src/legacy.ts':
            "export const a = 'ACME_CHAT'; // plugin-boundary: allow stored rows written before kinds were open\n// plugin-boundary: allow migration shim\nexport const b = 'BETA_SMS';\nexport const c = 'ACME_CHAT'; // plugin-boundary: allow\n",
        }),
      );
      assert.equal(code, 1);
      assert.deepEqual(report.pluginBoundary.violations.map((v) => v.at), ['apps/api/src/legacy.ts:4']);
      assert.deepEqual(report.pluginBoundary.escapes.map((e) => e.at), ['apps/api/src/legacy.ts:1', 'apps/api/src/legacy.ts:3']);
    });

    test('without a composition root the check is skipped', () => {
      const { code, report } = run(fixture({ files: { 'apps/api/src/route.ts': "export const k = 'ACME_CHAT';\n" } }));
      assert.equal(code, 0);
      assert.deepEqual(report.pluginBoundary.kinds, []);
      assert.equal(report.pluginBoundary.scanned, 0);
    });
  });

  test('findCycles reports self-loops and ignores acyclic graphs', () => {
    assert.deepEqual(findCycles(new Map([['a', ['b']], ['b', []]])), []);
    assert.deepEqual(findCycles(new Map([['a', ['a']]])), [{ members: ['a'], path: ['a', 'a'] }]);
  });
});
