/**
 * Unit tests for scripts/check-source-guards.mjs (T1.1.2). Run: node --test scripts/test/
 * Each test builds a throwaway workspace in the OS temp dir and runs the CLI against it.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { extractImports, findCycles } from '../check-source-guards.mjs';

const SCRIPT = join(dirname(fileURLToPath(import.meta.url)), '..', 'check-source-guards.mjs');
const roots = [];
after(() => roots.forEach((r) => rmSync(r, { recursive: true, force: true })));

/** A minimal clean workspace: domain ← auth ← api, plus a web app. Extra files/manifests override. */
function fixture({ files = {}, manifests = {} } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'ocso-guards-'));
  roots.push(root);
  const baseManifests = {
    'packages/domain': { name: '@ocso/domain' },
    'packages/auth': { name: '@ocso/auth', dependencies: { '@ocso/domain': 'workspace:*' } },
    'apps/api': { name: '@ocso/api', dependencies: { '@ocso/auth': 'workspace:*', '@ocso/domain': 'workspace:*' } },
    'apps/web': { name: '@ocso/web', dependencies: { '@ocso/domain': 'workspace:*' } },
  };
  const baseFiles = {
    'packages/domain/src/index.ts': "export const x = 1;\n",
    'packages/auth/src/index.ts': "import { x } from '@ocso/domain';\nexport const y = x;\n",
    'apps/api/src/main.ts': "import { y } from '@ocso/auth';\nimport type { Z } from './types.js';\nconsole.log(y);\n",
    'apps/api/src/types.ts': 'export type Z = string;\n',
    'apps/web/src/page.tsx': "import { x } from '@ocso/domain';\nexport default () => x;\n",
  };
  for (const [dir, manifest] of Object.entries({ ...baseManifests, ...manifests })) {
    mkdirSync(join(root, dir), { recursive: true });
    writeFileSync(join(root, dir, 'package.json'), JSON.stringify(manifest));
  }
  for (const [path, text] of Object.entries({ ...baseFiles, ...files })) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), text);
  }
  return root;
}

function run(root) {
  const res = spawnSync(process.execPath, [SCRIPT, '--json', '--root', root], { encoding: 'utf8' });
  assert.equal(res.stderr, '', res.stderr);
  return { code: res.status, report: JSON.parse(res.stdout) };
}

const lines = (n) => Array.from({ length: n }, (_, i) => `export const v${i} = ${i};`).join('\n') + '\n';

describe('check-source-guards', () => {
  test('a clean workspace passes', () => {
    const { code, report } = run(fixture());
    assert.equal(code, 0);
    assert.equal(report.ok, true);
    assert.equal(report.scanned, 5);
    assert.deepEqual(report.violations, []);
    assert.deepEqual(report.cycles, []);
  });

  test('a file over 500 lines fails', () => {
    const { code, report } = run(fixture({ files: { 'packages/auth/src/huge.ts': lines(501) } }));
    assert.equal(code, 1);
    assert.deepEqual(report.files, [{ path: 'packages/auth/src/huge.ts', lines: 501, status: 'FAIL' }]);
  });

  test('a file over 300 lines only warns', () => {
    const { code, report } = run(fixture({ files: { 'apps/api/src/big.ts': lines(301), 'apps/api/src/ok.ts': lines(300) } }));
    assert.equal(code, 0);
    assert.equal(report.warnings, 1);
    assert.deepEqual(report.files, [{ path: 'apps/api/src/big.ts', lines: 301, status: 'WARN' }]);
  });

  test('tests, declaration files and generated files are exempt from the size limit', () => {
    const root = fixture({
      files: {
        'packages/auth/src/big.test.ts': lines(900),
        'packages/auth/src/types.d.ts': lines(900),
        'packages/auth/src/gen.ts': `// @generated by a tool. Do not edit.\n${lines(900)}`,
      },
    });
    const { code, report } = run(root);
    assert.equal(code, 0);
    assert.deepEqual(report.files, []);
  });

  test('a package without src/ (Next.js layout) is scanned from its root, minus tests and configs', () => {
    const { code, report } = run(
      fixture({
        manifests: { 'apps/site': { name: '@ocso/site' } },
        files: {
          'apps/site/app/page.tsx': lines(501),
          'apps/site/next.config.ts': lines(900),
          'apps/site/e2e/flow.ts': lines(900),
          'apps/site/lib/api.ts': "import { boot } from '@ocso/api';\nexport const b = boot;\n",
        },
      }),
    );
    assert.equal(code, 1);
    assert.deepEqual(report.files, [{ path: 'apps/site/app/page.tsx', lines: 501, status: 'FAIL' }]);
    assert.deepEqual(report.violations.map((v) => `${v.rule} ${v.at}`), ['app-imports-app apps/site/lib/api.ts:1']);
  });

  test('a package importing an app fails (by name and by relative path)', () => {
    const { code, report } = run(
      fixture({
        files: {
          'packages/auth/src/bad.ts': "import { boot } from '@ocso/api';\nexport const b = boot;\n",
          'packages/auth/src/bad2.ts': "export { z } from '../../../apps/api/src/types.js';\n",
        },
      }),
    );
    assert.equal(code, 1);
    const rules = report.violations.map((v) => `${v.rule} ${v.at}`).sort();
    assert.deepEqual(rules, ['package-imports-app packages/auth/src/bad.ts:1', 'package-imports-app packages/auth/src/bad2.ts:1']);
  });

  test('an app importing another app fails, including dynamic imports and package.json deps', () => {
    const { code, report } = run(
      fixture({
        files: { 'apps/web/src/lazy.ts': "export const load = () => import(\n  '@ocso/api/client'\n);\n" },
        manifests: { 'apps/web': { name: '@ocso/web', dependencies: { '@ocso/domain': 'workspace:*', '@ocso/api': 'workspace:*' } } },
      }),
    );
    assert.equal(code, 1);
    const rules = report.violations.map((v) => `${v.rule} ${v.at}`).sort();
    assert.deepEqual(rules, ['app-imports-app apps/web/package.json', 'app-imports-app apps/web/src/lazy.ts:2']);
  });

  test('@ocso/domain importing another @ocso package fails', () => {
    const { code, report } = run(
      fixture({
        files: { 'packages/domain/src/leak.ts': "import type {\n  Principal,\n} from '@ocso/auth';\nexport type P = Principal;\n" },
      }),
    );
    assert.equal(code, 1);
    assert.equal(report.violations.length, 1);
    assert.equal(report.violations[0].rule, 'domain-imports-workspace');
    assert.equal(report.violations[0].at, 'packages/domain/src/leak.ts:3');
    // The same edge also closes a cycle only if declared; here it is source-only, so no cycle.
    assert.deepEqual(report.cycles, []);
  });

  test('relative imports into a sibling package fail', () => {
    const { code, report } = run(fixture({ files: { 'packages/auth/src/peek.ts': "import { x } from '../../domain/src/index.js';\nexport const p = x;\n" } }));
    assert.equal(code, 1);
    assert.equal(report.violations[0].rule, 'relative-cross-workspace');
  });

  test('imports inside comments, strings of other calls and template literals are ignored', () => {
    const src = [
      "// import { a } from '@ocso/api';",
      "/* export * from '@ocso/api'; */",
      "const doc = `import x from '@ocso/api'`;",
      "const re = /from '@ocso\\/api'/;",
      "const ratio = total / count / 2; import { real } from '@ocso/domain';",
    ].join('\n');
    assert.deepEqual(
      extractImports(src).map((i) => i.specifier),
      ['@ocso/domain'],
    );
  });

  test('dependency cycles between workspace packages are detected', () => {
    const { code, report } = run(
      fixture({
        manifests: {
          'packages/domain': { name: '@ocso/domain' },
          'packages/auth': { name: '@ocso/auth', dependencies: { '@ocso/domain': 'workspace:*', '@ocso/queue': 'workspace:*' } },
          'packages/queue': { name: '@ocso/queue', devDependencies: { '@ocso/db': 'workspace:*' } },
          'packages/db': { name: '@ocso/db', dependencies: { '@ocso/auth': 'workspace:*' } },
        },
      }),
    );
    assert.equal(code, 1);
    assert.equal(report.cycles.length, 1);
    assert.deepEqual(report.cycles[0].path, ['@ocso/auth', '@ocso/queue', '@ocso/db', '@ocso/auth']);
  });

  test('findCycles reports self-loops and ignores acyclic graphs', () => {
    assert.deepEqual(findCycles(new Map([['a', ['b']], ['b', []]])), []);
    assert.deepEqual(findCycles(new Map([['a', ['a']]])), [{ members: ['a'], path: ['a', 'a'] }]);
  });
});
