import { randomBytes } from 'node:crypto';
import { and, desc, eq, gte, sql } from 'drizzle-orm';
import { Permission, assertCan } from '@ocso/auth';
import { notFound, validation } from '@ocso/domain';
import { uuidv7, webhookDeliveries, webhookSubscriptions, type Db } from '@ocso/db';
import type { QueueAdapter } from '@ocso/queue';
import type { SecretStore } from '@ocso/secrets';
import { z } from 'zod';
import { recordAudit } from '../audit/audit.js';
import { assertPlatformWrite } from '../settings/platform-approvals.js';
import type { ActorContext } from '../shared/context.js';
import { isValidPattern } from './event-types.js';

const Patterns = z.array(z.string().trim().refine(isValidPattern, 'unknown event type')).min(1).max(40);
export const WebhookInput = z.object({
  name: z.string().trim().min(1).max(80),
  url: z.url({ protocol: /^https$/ }).max(2_000),
  events: Patterns,
});
export type WebhookInput = z.infer<typeof WebhookInput>;
export const WebhookPatch = z.object({ name: z.string().trim().min(1).max(80).optional(), url: z.url({ protocol: /^https$/ }).max(2_000).optional(), events: Patterns.optional(), enabled: z.boolean().optional() });
export type WebhookPatch = z.infer<typeof WebhookPatch>;
/** What an approval changes (enabling is ACTIVATE, disabling a stop action). */
export const WebhookChange = WebhookPatch.omit({ enabled: true }).strict();
export type WebhookChange = z.infer<typeof WebhookChange>;

export interface WebhookView {
  id: string;
  name: string;
  url: string;
  events: string[];
  enabled: boolean;
  createdAt: string;
  last24h: { sent: number; failed: number; pending: number };
  lastDeliveryAt: string | null;
}

const newSecret = () => `whsec_${randomBytes(24).toString('base64url')}`;

/**
 * Outbound event webhook subscriptions (PM/BUILD-PLAN E8.10). The signing
 * secret is generated by OCSO, stored in the SecretStore and shown once.
 *
 * Maker–checker (PM/research/11 §4, webhook-approval.ts): a subscription is
 * created disabled (a draft); enabling is an ACTIVATE proposal, deleting a
 * DELETE proposal, and once approved every change is an UPDATE proposal.
 * Disabling and rotating the signing secret (a revocation) are immediate.
 */
export class WebhookService {
  constructor(
    private readonly db: Db,
    private readonly secrets: SecretStore,
    private readonly queue: QueueAdapter,
  ) {}

  async list(actor: ActorContext): Promise<WebhookView[]> {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    const subs = await this.db.select().from(webhookSubscriptions).orderBy(webhookSubscriptions.name);
    const since = new Date(Date.now() - 24 * 3600_000);
    const stats = await this.db
      .select({ id: webhookDeliveries.subscriptionId, status: webhookDeliveries.status, n: sql<number>`count(*)::int`, last: sql<Date | null>`max(${webhookDeliveries.sentAt})` })
      .from(webhookDeliveries)
      .where(gte(webhookDeliveries.createdAt, since))
      .groupBy(webhookDeliveries.subscriptionId, webhookDeliveries.status);
    return subs.map((s) => {
      const mine = stats.filter((r) => r.id === s.id);
      const count = (status: string) => mine.find((r) => r.status === status)?.n ?? 0;
      const last = mine.map((r) => r.last).filter((d): d is Date => d !== null).sort((a, b) => +b - +a)[0];
      return { id: s.id, name: s.name, url: s.url, events: s.events, enabled: s.enabled, createdAt: s.createdAt.toISOString(), last24h: { sent: count('SENT'), failed: count('FAILED'), pending: count('PENDING') }, lastDeliveryAt: last ? new Date(last).toISOString() : null };
    });
  }

  async create(actor: ActorContext, input: WebhookInput): Promise<{ id: string; signingSecret: string }> {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    const signingSecret = newSecret();
    const secret = await this.secrets.put({ name: `webhook-${input.name}`, kind: 'WEBHOOK_SECRET', value: signingSecret, usedBy: `webhook:${input.name}` });
    const id = uuidv7();
    await this.db.transaction(async (tx) => {
      // A draft: nothing is delivered until the ACTIVATE proposal is approved.
      await tx.insert(webhookSubscriptions).values({ id, name: input.name, url: input.url, events: input.events, signingSecretRef: secret.ref, enabled: false, createdBy: actor.principal!.userId });
      await recordAudit(tx, actor, { action: 'webhook.create', targetType: 'webhook', targetId: id, summary: `Webhook ${input.name} → ${new URL(input.url).host} (${input.events.join(', ')}), disabled until approved` });
    });
    return { id, signingSecret };
  }

  /** A draft's name, URL or events (409 approval_required once approved: an UPDATE proposal). */
  async update(actor: ActorContext, id: string, patch: WebhookChange): Promise<void> {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    const existing = await this.get(id);
    await this.db.transaction(async (tx) => {
      await assertPlatformWrite(tx, 'webhook_subscription', id);
      await tx.update(webhookSubscriptions).set({ ...patch, updatedAt: new Date() }).where(eq(webhookSubscriptions.id, id));
      await recordAudit(tx, actor, { action: 'webhook.update', targetType: 'webhook', targetId: id, summary: `Webhook ${existing.name} updated`, before: { url: existing.url, events: existing.events, enabled: existing.enabled }, after: patch });
    });
  }

  /** Stop action: immediate, never gated, allowed while a proposal is open. */
  async disable(actor: ActorContext, id: string): Promise<void> {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    const existing = await this.get(id);
    if (!existing.enabled) return;
    await this.db.transaction(async (tx) => {
      await tx.update(webhookSubscriptions).set({ enabled: false, updatedAt: new Date() }).where(eq(webhookSubscriptions.id, id));
      await recordAudit(tx, actor, { action: 'webhook.disable', targetType: 'webhook', targetId: id, summary: `Webhook ${existing.name} disabled`, before: { enabled: true }, after: { enabled: false } });
    });
  }

  async rotateSecret(actor: ActorContext, id: string): Promise<{ signingSecret: string }> {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    const existing = await this.get(id);
    const signingSecret = newSecret();
    await this.secrets.rotate(existing.signingSecretRef, signingSecret);
    await this.db.transaction((tx) => recordAudit(tx, actor, { action: 'webhook.rotate_secret', targetType: 'webhook', targetId: id, summary: `Webhook ${existing.name} signing secret rotated` }));
    return { signingSecret };
  }


  async deliveries(actor: ActorContext, id: string, status?: 'PENDING' | 'SENT' | 'FAILED') {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    await this.get(id);
    const where = status ? and(eq(webhookDeliveries.subscriptionId, id), eq(webhookDeliveries.status, status)) : eq(webhookDeliveries.subscriptionId, id);
    return this.db.select().from(webhookDeliveries).where(where).orderBy(desc(webhookDeliveries.createdAt)).limit(100);
  }

  /** Manual redelivery of a FAILED delivery (same event id; receivers dedupe on it). */
  async retry(actor: ActorContext, deliveryId: string): Promise<void> {
    assertCan(actor.principal!, Permission.WEBHOOKS_MANAGE);
    const [row] = await this.db.update(webhookDeliveries).set({ status: 'PENDING', attempts: 0, lastError: null }).where(and(eq(webhookDeliveries.id, deliveryId), eq(webhookDeliveries.status, 'FAILED'))).returning();
    if (!row) throw validation('not_retryable', 'Only failed deliveries can be retried');
    await this.queue.publish('webhook.deliver', { deliveryId }, { dedupeKey: `webhook:${deliveryId}:manual:${Date.now()}` });
  }

  async get(id: string) {
    const [row] = await this.db.select().from(webhookSubscriptions).where(eq(webhookSubscriptions.id, id));
    if (!row) throw notFound('webhook', id);
    return row;
  }
}
